apiVersion: v1
# settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: ta3-configuration
spec:
  selector:
    matchLabels:
      role: ta3
  env:
  - name: D3MPLASMASOCKET
    value: "/local/plasma.sock"
  - name: LUCKY
    value: "4-leaf-clover"
  volumes:
  - mountPath: "/ravens_volume"
    name: "ravens-volume"
    readOnly: false
