# ---------------------------------------
# Configmap used by:
#   main (TA3), celery-worker, rook-service
# ---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: ravens-config-d3m
data:
  # D3MPROBLEMPATH set to get initial CI working
  #   - assumes /input is a top level of https://gitlab.datadrivendiscovery.org/d3m/datasets
  D3MPROBLEMPATH: "/input/TRAIN/problem_TRAIN/problemDoc.json"
  # --------------------------------
  # volumes configured through CI k8s preset
  # --------------------------------
  D3MRUN: "ta2ta3"
  D3MINPUTDIR: "/input"
  D3MOUTPUTDIR: "/output"
  D3MLOCALDIR: "/local"
  D3MSTATICDIR: "/static"
  # --------------------------------
  # Only used by the TA2
  # --------------------------------
  D3MCPU: "1"
  D3MRAM: "512Mi"
  D3MTIMEOUT: "3600"
  # --------------------------------
  # -- deprecated --
  # --------------------------------
  # D3MPORT: "45042"
