---
# --------------------------------
# CI system.yml template - v.001
# --------------------------------
{{ ravens_config_d3m }}
---
{{ ravens_config_ta3 }}
---
apiVersion: v1
kind: Pod
metadata:
  name: tworavensweb
  labels:
    app: ta3
spec:
  restartPolicy: Never
  volumes:
    # ----------------------------
    # TA3 specific volume
    #  - may be shared with a TA2
    # ----------------------------
    - name: ravens-volume
      emptyDir: {}
  containers:
  # -------------------------
  # 1 of 6: main (web app)
  # -------------------------
  - name: main
    image: tworavens/ravens-main:latest
    imagePullPolicy: IfNotPresent
    command: ["d3m_start.sh"]
    resources:
      requests:
        memory: 1Gi
        cpu: "0.75"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
{{ container_volume_mounts }}
    envFrom:
      - configMapRef:
          name: ravens-config-d3m
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
  # -------------------------
  # 2 of 6: Ravens nginx
  # -------------------------
  - name: ravens-nginx
    image: tworavens/ravens-nginx:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: "0.3"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    volumeMounts:
{{ container_volume_mounts }}
  # -------------------------
  # 3 of 6: redis
  # -------------------------
  - name: redis
    image: redis:4.0
    resources:
      requests:
        memory: 100Mi
        cpu: "0.3"
    ports:
    - containerPort: 6379
  # -------------------------
  # 4 of 6: celery worker
  # -------------------------
  - name: celery-worker
    image: tworavens/ravens-main:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-main:latest
    imagePullPolicy: IfNotPresent
    command: ['celery', '-A', 'tworavensproject', 'worker', '-l', 'info']
    resources:
      requests:
        memory: 512Mi
        cpu: "0.6"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
{{ container_volume_mounts }}
    # ---------------------------------
    # environment variables passed to container
    # ---------------------------------
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
      - configMapRef:
          name: ravens-config-d3m
  # -------------------------
  # 5 of 6: mongo
  # -------------------------
  - name: mongo-2ravens
    image: mongo
    resources:
      requests:
        memory: 512Mi
        cpu: "0.3"
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between TwoRavens and rook
      # - has some test data if needed
      # ----------------------------------
      - name: ravens-volume
        # directory location on host
        #path: /db_mongo
        mountPath: /data/db
        readOnly: false
  # -------------------------
  # 6 of 6: rook
  # -------------------------
  - name: rook-service
    image: tworavens/ravens-r-service:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-r-service:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 512Mi
        cpu: "0.75"
    volumeMounts:
{{ container_volume_mounts }}
    ports:
      - containerPort: 8000
        name: http
        protocol: TCP
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
    envFrom:
      - configMapRef:
          name: ravens-config-d3m
    env:
      # ----------------------------------
      # Also set to "yes" in the Dockerfile
      # ----------------------------------
      - name: ROOK_USE_PRODUCTION_MODE
        value: "yes"
  #
  # regcred notes: https://datadrivendiscovery.org/wiki/display/gov/Pulling-From-Private-Repository
  #
  imagePullSecrets:
  - name: regcred
