---
# Testing persistentVolume and persistentVolumeClaim
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  storageClassName: "twopod-10g-pv-1"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "gce-pd-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: "twopod-10g-pv-1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
