apiVersion: v1
kind: Service
metadata:
  name: ravens-main
  labels:
    app: ravens-main
    role: main
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    app: ravens-main
    role: main
    tier: backend
