apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  backend:
    serviceName: just-nginx-app
    servicePort: 80
---
#
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-raven
  name: just-web-service
spec:
  type: NodePort
  #loadBalancerIP: 104.197.235.238  # 2ravens.org
  selector:
    app: just-nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: just-pod
  labels:
    app: just-nginx-app
spec:
  restartPolicy: Always
  volumes:
    - name: ravens-volume
      emptyDir: {}
  containers:
  # -------------------------
  # 1 of 1:  nginx
  # -------------------------
  - name: just-nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    # ----------------------------------
    # shared between TwoRavens and rook
    # - also has static files to serve
    # ----------------------------------
    volumeMounts:
    - name: ravens-volume
      mountPath: /ravens_volume
      readOnly: false
