# ------------------------
# Shared env variables
# Used by containers:
#  - ta3-main
#  - celery-woker
#  - ta2-main (ignores django/db related variables)
# ------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: ravens-d3m-config
  namespace: default
data:
  # ----------------------------------
  # D3M summer eval variables
  # ref: https://goo.gl/L1J9i5
  # ----------------------------------
  D3MRUN: ta2ta3
  D3MINPUTDIR: "/ravens_volume/test_data/196_autoMpg"
  #D3MINPUTDIR: "/ravens_volume/test_data/185_baseball"
  D3MOUTPUTDIR: "/ravens_volume/test_output"
  D3MPROBLEMPATH: "/ravens_volume/test_data/196_autoMpg/TRAIN/problem_TRAIN/problemDoc.json"
  #
  # D3MLOCALDIR needs something better, but for now...
  #
  D3MLOCALDIR: "/ravens_volume/test_output"
  #
  # D3MSTATICDIR needs something better, but for now...
  #
  D3MSTATICDIR: "/ravens_volume/test_output"
  #
  D3MCPU: "1"
  D3MRAM: "1048576000"
  #D3MRAM: "512Mi"
  D3MTIMEOUT: "10"
