apiVersion: v1
kind: Service
metadata:
  name: tworavensweb
  labels:
    app: tworavens
spec:
  selector:
    app: tworavens
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 35.190.87.43
