# Load balancer for DM
# Note: Readiness probes removed for ta3/rook -- they need to be retimed
#
apiVersion: v1
kind: Service
metadata:
  name: two-ravens-d3m
spec:
  type: LoadBalancer
  #
  # range reference: https://datadrivendiscovery.org/wiki/display/gov/Creating+Services
  # proxy tool: https://proxy.datadrivendiscovery.org
  #
  loadBalancerIP: {{ loadBalancerIP }}  # test IP; valid range: 10.108.25.1-10.108.30.254
  selector:
    role: ta3
  ports:
    - name: http
      port: 80
      targetPort: 80
