---
#
# Storage for event data **files**
#
apiVersion: v1
kind: PersistentVolume
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
metadata:
  name: storage-event-data-files
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
#
# Storage for **MySQL files**
#
apiVersion: v1
kind: PersistentVolume
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
metadata:
  name: storage-event-data-mysql
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
