# ---------------------------------------
# Configmap used by:
#   main (TA3), celery-worker, rook-service
# ---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: ravens-config-d3m
data:
  # D3MPROBLEMPATH set to get initial CI working
  #   - assumes /input is a top level of https://gitlab.datadrivendiscovery.org/d3m/datasets
  D3MPROBLEMPATH: "/input/seed_datasets_data_augmentation/DA_college_debt/TRAIN/problem_TRAIN/problemDoc.json"
