# ---------------------------------------
# Configmap used by:
#   main (TA3), celery-worker, rook-service
# ---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: ravens-config-ta3
data:
  #
  # Reference to the gRPC server using the pod name and TA2 port
  #
  #TA2_TEST_SERVER_URL: "ta2:45042"
  TA2_TEST_SERVER_URL: "tworavensweb:45042"
  #
  # TA3 specific
  #
  DJANGO_SETTINGS_MODULE: "tworavensproject.settings.dev_container2"
  LOCAL_SETUP_DIR: /ravens_volume/2ravens_local_setup
  TA2_STATIC_TEST_MODE: "False"
  DEBUG: "False"
  #
  # Url to TA3 R/rook web service
  R_DEV_SERVER_BASE: "http://localhost:8000/custom/"
  #
  # Redis
  REDIS_HOST: localhost
  #
  # valid values: "ws://" and  "wss://"
  WEBSOCKET_PREFIX: "wss://"
  #
  # Mongo db name
  TWORAVENS_MONGO_DB_NAME: "tworavens_mongo"
  # Not a real key, only for CI
  SECRET_KEY: f!@0^(dl94d8#c4t#!xjk412345w2vzo)u@v6s4re&+gqz3s2&
  MONGO_CONNECTION_STRING: "mongodb://localhost:27017"
