---
# TA3 template file to comply with Winter 2019
#   https://datadrivendiscovery.org/wiki/pages/viewpage.action?pageId=11276800
#
# Note: Readiness probes removed for ta3/rook -- they need to be retimed
#
apiVersion: v1
kind: Service
metadata:
  name: two-ravens-d3m
spec:
  type: LoadBalancer
  #
  # range reference: https://datadrivendiscovery.org/wiki/display/gov/Creating+Services
  # proxy tool: https://proxy.datadrivendiscovery.org
  #
  loadBalancerIP: {{ loadBalancerIP }}  # test IP; valid range: 10.108.25.1-10.108.30.254
  selector:
    app: ta3
  ports:
    - name: http
      port: 80
      targetPort: 80
---
{{ ravens_config_d3m }}
---
{{ ravens_config_ta3 }}
---
apiVersion: v1
kind: Pod
metadata:
  name: tworavensweb
  labels:
    app: ta3
spec:
  restartPolicy: Never
  volumes:
    - name: ravens-volume
      emptyDir: {}
    # ----------------------------
    # Volumes for jump server data
    # ----------------------------
    - name: input-data
      hostPath:
        path: {{ eval_dataset_path }}
        type: Directory
    - name: static-data
      hostPath:
        path: {{ static_dataset_path }}
        type: Directory
    - name: output-data
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
  containers:
  # -------------------------
  # 1 of 6: main (web app)
  # -------------------------
  - name: main
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-main:latest
    image: tworavens/ravens-main:latest
    imagePullPolicy: IfNotPresent
    command: ["d3m_start.sh"]
    resources:
      requests:
        memory: 1Gi
        cpu: "0.75"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: "/ravens_volume"
        name: "ravens-volume"
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    envFrom:
      - configMapRef:
          name: ravens-config-d3m
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
  # -------------------------
  # 2 of 6: Ravens nginx
  # -------------------------
  - name: ravens-nginx
    image: tworavens/ravens-nginx:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: "0.3"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: "/ravens_volume"
        name: "ravens-volume"
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
  # -------------------------
  # 3 of 6: redis
  # -------------------------
  - name: redis
    image: redis:4.0
    resources:
      requests:
        memory: 100Mi
        cpu: "0.3"
    ports:
    - containerPort: 6379
  # -------------------------
  # 4 of 6: celery worker
  # -------------------------
  - name: celery-worker
    image: tworavens/ravens-main:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-main:latest
    imagePullPolicy: IfNotPresent
    command: ['celery', '-A', 'tworavensproject', 'worker', '-l', 'info']
    resources:
      requests:
        memory: 512Mi
        cpu: "0.6"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: "/ravens_volume"
        name: "ravens-volume"
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    # ---------------------------------
    # environment variables passed to container
    # ---------------------------------
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
      - configMapRef:
          name: ravens-config-d3m
  # -------------------------
  # 5 of 6: mongo
  # -------------------------
  - name: mongo-2ravens
    image: mongo
    resources:
      requests:
        memory: 512Mi
        cpu: "0.3"
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between TwoRavens and rook
      # - has some test data if needed
      # ----------------------------------
      - name: ravens-volume
        # directory location on host
        #path: /db_mongo
        mountPath: /data/db
        readOnly: false
  # -------------------------
  # 6 of 6: rook
  # -------------------------
  - name: rook-service
    image: tworavens/ravens-r-service:latest
    # image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-r-service:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 512Mi
        cpu: "0.75"
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: "/ravens_volume"
        name: "ravens-volume"
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    ports:
      - containerPort: 8000
        name: http
        protocol: TCP
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
    envFrom:
      - configMapRef:
          name: ravens-config-d3m
    env:
      # ----------------------------------
      # Also set to "yes" in the Dockerfile
      # ----------------------------------
      - name: ROOK_USE_PRODUCTION_MODE
        value: "yes"
  # -------------------------
  # 7 of 7: TA2
  # -------------------------
  - name: ta2-main
    image: registry.datadrivendiscovery.org/kyao/ta3ta2/ta3ta2-image:latest
    # Brown TA2
    # image: registry.datadrivendiscovery.org/ta2-submissions/ta2-brown/ta2-brown:submission
    #image: registry.datadrivendiscovery.org/tworavens/tworavens-deploy/ta2_server:live
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    ports:
      - containerPort: 45042
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: "/ravens_volume"
        name: "ravens-volume"
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    envFrom:
      - configMapRef:
          name: ravens-config-d3m
    envFrom:
      - configMapRef:
          name: ravens-config-ta3
  #
  # regcred notes: https://datadrivendiscovery.org/wiki/display/gov/Pulling-From-Private-Repository
  #
  imagePullSecrets:
  - name: regcred
