---
# This is Configuration for the DM infrastructure that uses:
#
#   (1) ISI TA2 on the datadrivendiscovery gitlab
#   (2) TwoRavens TA3, using *DockerHub* public images
#
apiVersion: v1
kind: Service
metadata:
  name: two-ravens-d3m
spec:
  type: LoadBalancer
  #
  # range reference: https://datadrivendiscovery.org/wiki/display/gov/Creating+Services
  # proxy tool: https://proxy.datadrivendiscovery.org
  #
  loadBalancerIP: {{ loadBalancerIP }}  # test IP; valid range: 10.108.25.1-10.108.30.254
  selector:
    app: ta3
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# ---------------------------------------
# TA3 configmap used by:
#   ta3-main, rook-service, celery-worker
# ---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: ravens-django-config
data:
  DJANGO_SETTINGS_MODULE: "tworavensproject.settings.dev_container2"
  LOCAL_SETUP_DIR: /ravens_volume/2ravens_local_setup
  #
  # When TA2_STATIC_TEST_MODE is set to True, TA2 is ignored
  TA2_STATIC_TEST_MODE: "False"
  DEBUG: "False"
  #TA2_STATIC_TEST_MODE: "True"
  #
  # Reference to the gRPC server using the pod name and TA2 port
  TA2_TEST_SERVER_URL: "tworavensweb:45042"
  #
  # Url to TA3 R/rook web service
  R_DEV_SERVER_BASE: "http://localhost:8000/custom/"
  #
  # Redis
  REDIS_HOST: localhost
  #
  # valid values: "ws://" and  "wss://"
  WEBSOCKET_PREFIX: "wss://"
  #
  # Mongo db name; Mongo creds are in secrets
  TWORAVENS_MONGO_DB_NAME: "harvard"
---
apiVersion: v1
kind: Pod
metadata:
  name: tworavensweb
  labels:
    app: ta3
spec:
  restartPolicy: Never
  volumes:
    - name: ravens-volume
      emptyDir: {}
    # ----------------------------
    # Volumes for jump server data
    # ----------------------------
    - name: input-data
      hostPath:
        path: {{ eval_dataset_path }}
        type: Directory
    - name: static-data
      hostPath:
        path: {{ static_dataset_path }}
        type: Directory
    - name: output-data
      persistentVolumeClaim:
        claimName: eval-output-pv-claim
  containers:
  # -------------------------
  # 2 of 7: Ravens nginx
  # -------------------------
  - name: ravens-nginx
    #  image: registry.datadrivendiscovery.org/ta3-submissions/ta3-two-ravens/ravens-deploy-2019/ravens-nginx:latest
    image: tworavens/ravens-nginx:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 256Mi
        cpu: 1
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: /ravens_volume
        name: ravens-volume
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
  # -------------------------
  # 3 of 7: redis
  # -------------------------
  - name: redis
    image: redis:4.0
    resources:
      requests:
        memory: 100Mi
        cpu: 1
    ports:
    - containerPort: 6379
  # -------------------------
  # 4 of 7: TA3 main (web app)
  # -------------------------
  - name: ta3-main
    image: tworavens/ravens-main:latest
    #image: tworavens/ravens-main:develop
    imagePullPolicy: Always
    command: ["d3m_start.sh"]
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: /ravens_volume
        name: ravens-volume
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    envFrom:
      - configMapRef:
          name: ravens-django-config
    env:
      - name: MONGO_CONNECTION_STRING
        value: "mongodb://localhost:27017"
      - name: SECRET_KEY
        value: f!@0^(7v_!d8#c4t#!xjk433&xbw2vzo)u@v6s9pc&+gqz3s2&
      # ----------------------------------
      # D3M winter eval variables
      # ref: https://datadrivendiscovery.org/wiki/pages/viewpage.action?pageId=11276800
      # ----------------------------------
      #
      # Note: D3MPORT is from the summer but used for compatibility with older TA2s
      #
      - name: D3MPORT
        value: "45042"
      #
      - name: D3MRUN
        value: "{{ D3MRUN }}"
      - name: D3MINPUTDIR
        value: "{{ D3MINPUTDIR }}"
      - name: D3MOUTPUTDIR
        value: "/output"
      - name: D3MLOCALDIR
        value: "/local"
      - name: D3MSTATICDIR
        value: "/static"
      - name: D3MPROBLEMPATH
        value: "{{ D3MPROBLEMPATH }}"
      - name: D3MLOCALDIR
        value: "{{ D3MLOCALDIR }}"
      - name: D3MCPU
        value: "1"
      - name: D3MRAM
        value: "524288000"
      - name: D3MTIMEOUT
        value: "3600"
      # ----------------------------------
      # END: D3M winter eval variables
      # ----------------------------------
  # -------------------------
  # 5 of 7: celery worker
  # -------------------------
  - name: celery-worker
    image: tworavens/ravens-main:latest
    imagePullPolicy: Always
    command: ['celery', '-A', 'tworavensproject', 'worker', '-l', 'info']
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: /ravens_volume
        name: ravens-volume
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    # ---------------------------------
    # environment variables passed to container
    # ---------------------------------
    envFrom:
      - configMapRef:
          name: ravens-django-config
    env:
      - name: SECRET_KEY
        value: f!@0^(7v_!d8#c4t#!xjk433&xbw2vzo)u@v6s9pc&+gqz3s2&
      - name: MONGO_CONNECTION_STRING
        value: "mongodb://localhost:27017"
      #- name: MONGO_CONNECTION_STRING
      #  valueFrom:
      #    secretKeyRef:
      #      name: dm-d3m-secrets
      #      key: MONGO_CONNECTION_STRING
      # ----------------------------------
      # D3M winter eval variables
      # ref: https://datadrivendiscovery.org/wiki/pages/viewpage.action?pageId=11276800
      # ----------------------------------
      #
      # Note: D3MPORT is from the summer but used for compatibility with older TA2s
      #
      - name: D3MPORT
        value: "45042"
      #
      - name: D3MRUN
        value: "{{ D3MRUN }}"
      - name: D3MINPUTDIR
        value: "{{ D3MINPUTDIR }}"
      - name: D3MOUTPUTDIR
        value: "/output"
      - name: D3MLOCALDIR
        value: "/local"
      - name: D3MSTATICDIR
        value: "/static"
      - name: D3MPROBLEMPATH
        value: "{{ D3MPROBLEMPATH }}"
      - name: D3MLOCALDIR
        value: "{{ D3MLOCALDIR }}"
      - name: D3MCPU
        value: "1"
      - name: D3MRAM
        value: "524288000"
      - name: D3MTIMEOUT
        value: "3600"
      # ----------------------------------
      # END: D3M winter eval variables
      # ----------------------------------
  # -------------------------
  # 6 of 7: mongo
  # -------------------------
  - name: mongo-2ravens
    image: mongo
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    ports:
      - containerPort: 27017
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between TwoRavens and rook
      # - has some test data if needed
      # ----------------------------------
      - name: ravens-volume
        # directory location on host
        #path: /db_mongo
        mountPath: /data/db
        readOnly: false
  # -------------------------
  # 7 of 7: rook
  # -------------------------
  - name: rook-service
    image: tworavens/ravens-r-service:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: /ravens_volume
        name: ravens-volume
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    ports:
      - containerPort: 8000
        name: http
        protocol: TCP
    envFrom:
      - configMapRef:
          name: ravens-django-config
    env:
      # ----------------------------------
      # Also set to "yes" in the Dockerfile
      # ----------------------------------
      - name: ROOK_USE_PRODUCTION_MODE
        value: "yes"
      # ----------------------------------
      # D3M winter eval variables
      # ref: https://datadrivendiscovery.org/wiki/pages/viewpage.action?pageId=11276800
      # ----------------------------------
      #
      # Note: D3MPORT is from the summer but used for compatibility with older TA2s
      #
      - name: D3MPORT
        value: "45042"
      #
      - name: D3MRUN
        value: "{{ D3MRUN }}"
      - name: D3MINPUTDIR
        value: "{{ D3MINPUTDIR }}"
      - name: D3MOUTPUTDIR
        value: "/output"
      - name: D3MLOCALDIR
        value: "/local"
      - name: D3MSTATICDIR
        value: "/static"
      - name: D3MPROBLEMPATH
        value: "{{ D3MPROBLEMPATH }}"
      - name: D3MLOCALDIR
        value: "{{ D3MLOCALDIR }}"
      - name: D3MCPU
        value: "1"
      - name: D3MRAM
        value: "524288000"
      - name: D3MTIMEOUT
        value: "3600"
      # ----------------------------------
      # END: D3M winter eval variables
      # ----------------------------------
  # -------------------------
  # 1 of 7: TA2
  # -------------------------
  - name: ta2-main
    # ISI TA2
    image: registry.datadrivendiscovery.org/kyao/ta3ta2/ta3ta2-image:latest
    imagePullPolicy: Always
    resources:
      requests:
        memory: 512Mi
        cpu: 1
    ports:
      - containerPort: 45042
        protocol: TCP
    volumeMounts:
      # ----------------------------------
      # shared between containers
      # ----------------------------------
      - mountPath: /ravens_volume
        name: ravens-volume
        readOnly: false
      # ----------------------
      # D3M config volume mounts
      # ----------------------
      - name: input-data
        mountPath: /input
        readOnly: true
      - name: output-data
        mountPath: /output
        readOnly: false
      - name: static-data
        mountPath: /static
        readOnly: true
      # ----------------------
      # END: D3M config volume mounts
      # ----------------------
    env:
      # ----------------------------------
      # D3M winter eval variables
      # ref: https://datadrivendiscovery.org/wiki/pages/viewpage.action?pageId=11276800
      # ----------------------------------
      #
      # Note: D3MPORT is from the summer but used for compatibility with older TA2s
      #
      - name: D3MPORT
        value: "45042"
      #
      - name: D3MRUN
        value: "{{ D3MRUN }}"
      - name: D3MINPUTDIR
        value: "{{ D3MINPUTDIR }}"
      - name: D3MOUTPUTDIR
        value: "/output"
      - name: D3MLOCALDIR
        value: "/local"
      - name: D3MSTATICDIR
        value: "/static"
      - name: D3MPROBLEMPATH
        value: "{{ D3MPROBLEMPATH }}"
      - name: D3MLOCALDIR
        value: "{{ D3MLOCALDIR }}"
      - name: D3MCPU
        value: "1"
      - name: D3MRAM
        value: "524288000"
      - name: D3MTIMEOUT
        value: "3600"
      # ----------------------------------
      # END: D3M winter eval variables
      # ----------------------------------
  #
  # regcred notes: https://datadrivendiscovery.org/wiki/display/gov/Pulling-From-Private-Repository
  #
  imagePullSecrets:
  - name: regcred
